--[[
	******************************************************************************
	* @name			:	Custom Font Service
	* @authors		:	Scrpt2r
	* @date			:	January 06 2026
	* @lastEdit		:	January 07 2026
	* @brief		:	A service for using non existing fonts in studio.
	* @version		:	0.3.0
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--customFontService.src.__index
return require(script.__main__)
